[project]
name = "daily-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "toml>=0.10.2",
]
